# Generated by Django 5.1.1 on 2024-11-12 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logica_hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='habitacion',
            table='habitaciones',
        ),
        migrations.AlterModelTable(
            name='reserva',
            table='reservas',
        ),
    ]
