# Generated by Django 5.1.1 on 2024-11-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logica_hotel', '0002_alter_habitacion_table_alter_reserva_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='room_type',
        ),
        migrations.AddField(
            model_name='habitacion',
            name='status',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
