# Generated by Django 5.1.3 on 2024-11-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_phone', models.CharField(max_length=20)),
                ('room_type', models.CharField(max_length=50)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('additional_notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
